const config = {
  appID: 'DREAMBUDS',
};

export const actionTypes = {
  VIEW_STATE_LOADING: 'VIEW_STATE_LOADING',
  WALLET_DISCONNECTED: 'WALLET_DISCONNECTED',
  WALLET_CONNECTED: 'WALLET_CONNECTED',
  GET_ALL_COLLECTIONS: 'GET_ALL_COLLECTIONS',
};


export default config;
